package com.jets.entity;
// Generated Apr 24, 2022, 1:52:59 AM by Hibernate Tools 6.0.0.Beta2


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="categories"
    ,catalog="ecommerceapi"
)
public class Categories  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Set<Products> products = new HashSet<Products>(0);

    public Categories() {
    }

	
   
    public Categories( String name, String description, Set<Products> products) {
    
       this.name = name;
       this.description = description;
       this.products = products;
    }
   
   @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Products> getProductses() {
        return this.products;
    }
    
    public void setProductses(Set<Products> products) {
        this.products = products;
    }




}


