package com.jets.entity;
// Generated Apr 24, 2022, 1:52:59 AM by Hibernate Tools 6.0.0.Beta2

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers", catalog = "ecommerceapi")
public class Customers implements java.io.Serializable {

    private int id;
    private String name;
    private String email;
    private String password;
    private Set<Orders> orderses = new HashSet<Orders>(0);
    private String authtoken;
    private String gender;

    public Customers() {
    }

    public String getAuthtoken() {
        return authtoken;
    }

    public void setAuthtoken(String authtoken) {
        this.authtoken = authtoken;
    }

    public Customers(String name, String email, String password, Set<Orders> orderses, String authtoken,String gender) {

        this.name = name;
        this.email = email;
        this.password = password;
        this.orderses = orderses;
        this.authtoken = authtoken;
        this.gender=gender;
    }
    @Column(name = "gender",  nullable = false)
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "email", nullable = false, length = 150)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

}
