package com.jets.entity;
// Generated Apr 24, 2022, 1:52:59 AM by Hibernate Tools 6.0.0.Beta2


// import jakarta.json.bind.annotation.JsonbTransient;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="ecommerceapi"
)
public class Products  implements java.io.Serializable {


     private Integer id;
     private Categories categories;
     private String name;
     private long price;
     private String description;
     private int quantity;
     private String image;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public Products() {
        
    }

	
    public Products(String name, long price, int quantity, String image) {
        this.name = name;
        this.price = price;
        this.quantity = quantity;
        this.image = image;
    }
    public Products(Categories categories, String name, long price, String description, int quantity, String image, Set<OrderDetails> orderDetailses) {
       this.categories = categories;
       this.name = name;
       this.price = price;
       this.description = description;
       this.quantity = quantity;
       this.image = image;
       this.orderDetailses = orderDetailses;
    }
   

    @Id 
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy=IDENTITY)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="price", nullable=false, precision=10, scale=0)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }

    
    @Column(name="description", length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="image", nullable=false, length=255)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


